export class CourseOutcomes {
  _id: string | undefined;
  curriculumId: string | undefined;
  curriculumName: string | undefined;
  termId: string | undefined;
  termName: string | undefined;
  termNo: string | undefined;
  courseTitle: string | undefined;
  courseId: string | undefined;
  coCode: string | undefined;
  coType: number | undefined;
  classHrs: number | undefined;
  labHrs: number | undefined;
  coCodeStatement: string | undefined;
  deliveryMethod: string | undefined;
  cognitiveDomain: string[] | undefined;
  createdAt: Date | undefined;
  updateAt: Date | undefined;
}
